name: Component Detection with CMake and vcpkg

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VCPKG_FEATURE_FLAGS: dependencygraph

jobs:
  cmake:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cruvixdev/stm32-ci:latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'  

      - name: Bootstrap vcpkg
        run: ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh

      - name: Configure with CMake
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug -DVCPKG_OVERLAY_TRIPLETS=./cmake -DVCPKG_TARGET_TRIPLET=gcc-arm-none-eabi-triplet -DCMAKE_TOOLCHAIN_FILE=./submodules/vcpkg/scripts/buildsystems/vcpkg.cmake -S . -B ./build -G Ninja

      - name: Build with CMake
        run: cmake --build build
